name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 🛎️
        uses: actions/checkout@v2
      - name: Install and Build 🔧
        run: |
          git status
          # npm run install
          # npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .
