name: gh-pages

on:
  push:
    branches: [ main ]

env:
  .

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Cache dependencies 📚
        uses: actions/setup-node@v2

      - name: Build 🔧
        run: |
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
